/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Usuario;


/**
 *
 * @author Emanuel Kuanzambi
 */
public class Home extends javax.swing.JFrame {
    private Usuario usuario;
      
    String role;

    public String getRole() {
        return role;
    }
   
    /**
     * Creates new form Home
    
     */
   
  public Home(String role) {
       this.role = role;
        initComponents();
        configurarAcessos();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        btnCadastrarPaciente = new javax.swing.JButton();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnAgendarConsulta = new javax.swing.JButton();
        btnHistoricoPaciente = new javax.swing.JButton();
        btnPrescricaoMedicamento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 6, 60));

        btnCadastrarPaciente.setBackground(new java.awt.Color(0, 6, 60));
        btnCadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarPaciente.setText("Cadastrar Paciente");
        btnCadastrarPaciente.setBorderPainted(false);
        btnCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacienteActionPerformed(evt);
            }
        });

        btnCadastrarFuncionario.setBackground(new java.awt.Color(0, 6, 60));
        btnCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarFuncionario.setText("Cadastrar Funcionário");
        btnCadastrarFuncionario.setBorderPainted(false);
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btnAgendarConsulta.setBackground(new java.awt.Color(0, 6, 60));
        btnAgendarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgendarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarConsulta.setText("Agendar Consulta");
        btnAgendarConsulta.setBorderPainted(false);
        btnAgendarConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarConsultaActionPerformed(evt);
            }
        });

        btnHistoricoPaciente.setBackground(new java.awt.Color(0, 6, 60));
        btnHistoricoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHistoricoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoricoPaciente.setText("Histórico dos Pacientes");
        btnHistoricoPaciente.setBorderPainted(false);
        btnHistoricoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoPacienteActionPerformed(evt);
            }
        });

        btnPrescricaoMedicamento.setBackground(new java.awt.Color(0, 6, 60));
        btnPrescricaoMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPrescricaoMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescricaoMedicamento.setText("Prescrição de Medicamentos");
        btnPrescricaoMedicamento.setBorderPainted(false);
        btnPrescricaoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescricaoMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgendarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrescricaoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistoricoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnCadastrarPaciente)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarConsulta)
                .addGap(18, 18, 18)
                .addComponent(btnHistoricoPaciente)
                .addGap(18, 18, 18)
                .addComponent(btnPrescricaoMedicamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Emanuel Lucas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Imagens/health-medical-insurance-vector-28999951(2).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2)
                        .addGap(0, 208, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void btnHistoricoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoPacienteActionPerformed
Historico_paciente telaHist = new Historico_paciente();
telaHist.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btnHistoricoPacienteActionPerformed

    private void btnAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarConsultaActionPerformed
  Agendar_Consulta telaConsulta = new Agendar_Consulta();
  telaConsulta.setVisible(true);
  this.setVisible(false);
    }//GEN-LAST:event_btnAgendarConsultaActionPerformed

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
  Cadastro_de_paciente telaPaciente = new Cadastro_de_paciente();
  telaPaciente.setVisible(true);
  this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed

    private void btnPrescricaoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescricaoMedicamentoActionPerformed
Prescrição_de_Medicamentos telaPres = new Prescrição_de_Medicamentos();
telaPres.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btnPrescricaoMedicamentoActionPerformed

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
Cadastrar_Funcionario telaFuncionario = new Cadastrar_Funcionario();
telaFuncionario.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void configurarAcessos() {
        if ("admin".equals(role)) {
            btnCadastrarFuncionario.setEnabled(true);
            btnCadastrarPaciente.setEnabled(true);
            btnAgendarConsulta.setEnabled(true);
            btnPrescricaoMedicamento.setEnabled(true);
            btnHistoricoPaciente.setEnabled(true);   
          }
        
        if ("medico".equals(role)){
            btnCadastrarFuncionario.setVisible(false);
            btnCadastrarPaciente.setVisible(false);
            btnAgendarConsulta.setVisible(false);
            btnPrescricaoMedicamento.setEnabled(true);
            btnHistoricoPaciente.setEnabled(true); 
        }
        
        if ("secretario".equals(role)){
            btnCadastrarFuncionario.setEnabled(false);
            btnCadastrarPaciente.setEnabled(true);
            btnAgendarConsulta.setEnabled(true);
            btnPrescricaoMedicamento.setEnabled(false);
            btnHistoricoPaciente.setEnabled(true); 
        }
          
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Usuario usuario;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarConsulta;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JButton btnHistoricoPaciente;
    private javax.swing.JButton btnPrescricaoMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
